# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import numpy as np
a = np.arange(11, 20).reshape(3, 3)
print(a)
b = np.arange(21, 30).reshape(3, 3)
print(b)
# c = np.vstack((a, b))
c = np.concatenate((a, b), axis=0)
print(c)
# d = np.hstack((a, b))
d = np.concatenate((a, b), axis=1)
print(d)
e = np.dstack((a, b))
print(e)
a = a.ravel()
print(a)
b = b.ravel()
print(b)
f = np.row_stack((a, b))
print(f)
# g = np.hstack((a.reshape(-1, 1), b.reshape(-1, 1)))
g = np.column_stack((a, b))
print(g)